/* tslint:disable */
/* eslint-disable */
/**
 * HostBoost
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { BaseResponse } from '../models';
// @ts-ignore
import type { HostPostRequest } from '../models';
// @ts-ignore
import type { QueryHostListResponse } from '../models';
// @ts-ignore
import type { QueryHostResponse } from '../models';
/**
 * HostApi - axios parameter creator
 * @export
 */
export const HostApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary deleteHost
         * @param {HostPostRequest} [hostPostRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hostDelete: async (hostPostRequest?: HostPostRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/host`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(hostPostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary getHost
         * @param {string} [domain] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hostGet: async (domain?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/host`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (domain !== undefined) {
                localVarQueryParameter['domain'] = domain;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary getHostList
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hostListGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/host/list`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary addHost
         * @param {HostPostRequest} [hostPostRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hostPost: async (hostPostRequest?: HostPostRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/host`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(hostPostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * HostApi - functional programming interface
 * @export
 */
export const HostApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = HostApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary deleteHost
         * @param {HostPostRequest} [hostPostRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async hostDelete(hostPostRequest?: HostPostRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.hostDelete(hostPostRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HostApi.hostDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary getHost
         * @param {string} [domain] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async hostGet(domain?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QueryHostResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.hostGet(domain, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HostApi.hostGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary getHostList
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async hostListGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QueryHostListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.hostListGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HostApi.hostListGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary addHost
         * @param {HostPostRequest} [hostPostRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async hostPost(hostPostRequest?: HostPostRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.hostPost(hostPostRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HostApi.hostPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * HostApi - factory interface
 * @export
 */
export const HostApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = HostApiFp(configuration)
    return {
        /**
         * 
         * @summary deleteHost
         * @param {HostPostRequest} [hostPostRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hostDelete(hostPostRequest?: HostPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponse> {
            return localVarFp.hostDelete(hostPostRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary getHost
         * @param {string} [domain] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hostGet(domain?: string, options?: RawAxiosRequestConfig): AxiosPromise<QueryHostResponse> {
            return localVarFp.hostGet(domain, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary getHostList
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hostListGet(options?: RawAxiosRequestConfig): AxiosPromise<QueryHostListResponse> {
            return localVarFp.hostListGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary addHost
         * @param {HostPostRequest} [hostPostRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hostPost(hostPostRequest?: HostPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponse> {
            return localVarFp.hostPost(hostPostRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * HostApi - object-oriented interface
 * @export
 * @class HostApi
 * @extends {BaseAPI}
 */
export class HostApi extends BaseAPI {
    /**
     * 
     * @summary deleteHost
     * @param {HostPostRequest} [hostPostRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HostApi
     */
    public hostDelete(hostPostRequest?: HostPostRequest, options?: RawAxiosRequestConfig) {
        return HostApiFp(this.configuration).hostDelete(hostPostRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary getHost
     * @param {string} [domain] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HostApi
     */
    public hostGet(domain?: string, options?: RawAxiosRequestConfig) {
        return HostApiFp(this.configuration).hostGet(domain, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary getHostList
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HostApi
     */
    public hostListGet(options?: RawAxiosRequestConfig) {
        return HostApiFp(this.configuration).hostListGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary addHost
     * @param {HostPostRequest} [hostPostRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HostApi
     */
    public hostPost(hostPostRequest?: HostPostRequest, options?: RawAxiosRequestConfig) {
        return HostApiFp(this.configuration).hostPost(hostPostRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

