/* tslint:disable */
/* eslint-disable */
/**
 * HostBoost
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { BaseResponse } from '../models';
// @ts-ignore
import type { OptRequest } from '../models';
// @ts-ignore
import type { OptVo } from '../models';
/**
 * OptApi - axios parameter creator
 * @export
 */
export const OptApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 当接口效果不理想时,调用该接口轮换到下一个优选 IP, 并将原 IP 删除
         * @summary changeOpt
         * @param {string} [type] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        optChangeGet: async (type?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/opt/change`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (type !== undefined) {
                localVarQueryParameter['type'] = type;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 获取当前正在使用的优选 IP 信息
         * @summary getCurrentOpt
         * @param {string} [type] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        optGet: async (type?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/opt`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (type !== undefined) {
                localVarQueryParameter['type'] = type;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 上报优选 IP 的接口, 由 OPT 调用将有选好的 IP 发送给 MGR
         * @summary updateOpt
         * @param {OptRequest} [optRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        optReportPost: async (optRequest?: OptRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/opt/report`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(optRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * OptApi - functional programming interface
 * @export
 */
export const OptApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = OptApiAxiosParamCreator(configuration)
    return {
        /**
         * 当接口效果不理想时,调用该接口轮换到下一个优选 IP, 并将原 IP 删除
         * @summary changeOpt
         * @param {string} [type] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async optChangeGet(type?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.optChangeGet(type, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OptApi.optChangeGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 获取当前正在使用的优选 IP 信息
         * @summary getCurrentOpt
         * @param {string} [type] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async optGet(type?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OptVo>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.optGet(type, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OptApi.optGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 上报优选 IP 的接口, 由 OPT 调用将有选好的 IP 发送给 MGR
         * @summary updateOpt
         * @param {OptRequest} [optRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async optReportPost(optRequest?: OptRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.optReportPost(optRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OptApi.optReportPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * OptApi - factory interface
 * @export
 */
export const OptApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = OptApiFp(configuration)
    return {
        /**
         * 当接口效果不理想时,调用该接口轮换到下一个优选 IP, 并将原 IP 删除
         * @summary changeOpt
         * @param {string} [type] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        optChangeGet(type?: string, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponse> {
            return localVarFp.optChangeGet(type, options).then((request) => request(axios, basePath));
        },
        /**
         * 获取当前正在使用的优选 IP 信息
         * @summary getCurrentOpt
         * @param {string} [type] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        optGet(type?: string, options?: RawAxiosRequestConfig): AxiosPromise<OptVo> {
            return localVarFp.optGet(type, options).then((request) => request(axios, basePath));
        },
        /**
         * 上报优选 IP 的接口, 由 OPT 调用将有选好的 IP 发送给 MGR
         * @summary updateOpt
         * @param {OptRequest} [optRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        optReportPost(optRequest?: OptRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponse> {
            return localVarFp.optReportPost(optRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * OptApi - object-oriented interface
 * @export
 * @class OptApi
 * @extends {BaseAPI}
 */
export class OptApi extends BaseAPI {
    /**
     * 当接口效果不理想时,调用该接口轮换到下一个优选 IP, 并将原 IP 删除
     * @summary changeOpt
     * @param {string} [type] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OptApi
     */
    public optChangeGet(type?: string, options?: RawAxiosRequestConfig) {
        return OptApiFp(this.configuration).optChangeGet(type, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 获取当前正在使用的优选 IP 信息
     * @summary getCurrentOpt
     * @param {string} [type] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OptApi
     */
    public optGet(type?: string, options?: RawAxiosRequestConfig) {
        return OptApiFp(this.configuration).optGet(type, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 上报优选 IP 的接口, 由 OPT 调用将有选好的 IP 发送给 MGR
     * @summary updateOpt
     * @param {OptRequest} [optRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OptApi
     */
    public optReportPost(optRequest?: OptRequest, options?: RawAxiosRequestConfig) {
        return OptApiFp(this.configuration).optReportPost(optRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

