/* tslint:disable */
/* eslint-disable */
/**
 * HostBoost
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DomainDetail } from './domain-detail';

/**
 * 
 * @export
 * @interface DetailResponse
 */
export interface DetailResponse {
    /**
     * 
     * @type {string}
     * @memberof DetailResponse
     */
    'code': string;
    /**
     * 
     * @type {string}
     * @memberof DetailResponse
     */
    'message': string;
    /**
     * 
     * @type {DomainDetail}
     * @memberof DetailResponse
     */
    'data': DomainDetail;
}

