/* tslint:disable */
/* eslint-disable */
/**
 * HostBoost
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { HostVo } from './host-vo';

/**
 * 
 * @export
 * @interface QueryHostResponse
 */
export interface QueryHostResponse {
    /**
     * 
     * @type {number}
     * @memberof QueryHostResponse
     */
    'code': number;
    /**
     * 
     * @type {string}
     * @memberof QueryHostResponse
     */
    'message': string;
    /**
     * 
     * @type {HostVo}
     * @memberof QueryHostResponse
     */
    'data': HostVo;
}

